# Generated by Copilot for packet decryption tracking

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stridetastic_api", "0006_add_tcp_interface_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="packet",
            name="how_decrypted",
            field=models.CharField(
                choices=[
                    ("not_decrypted", "Not decrypted"),
                    ("aes", "AES"),
                    ("pki", "PKI"),
                ],
                default="not_decrypted",
                help_text="How the packet payload was decrypted (or not).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="packetdata",
            name="how_decrypted",
            field=models.CharField(
                choices=[
                    ("not_decrypted", "Not decrypted"),
                    ("aes", "AES"),
                    ("pki", "PKI"),
                ],
                default="not_decrypted",
                help_text="How the packet payload was decrypted (or not).",
                max_length=32,
            ),
        ),
    ]
