# Generated by Copilot for keepalive configuration and presence history

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stridetastic_api", "0007_packet_how_decrypted"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeepaliveConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_enforcer",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "offline_after_seconds",
                    models.PositiveIntegerField(
                        default=3600,
                        help_text="Seconds of inactivity before a node is considered offline.",
                    ),
                ),
                (
                    "check_interval_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="How often the keepalive check should run.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "All nodes"),
                            ("selected", "Selected nodes"),
                            ("virtual_only", "Virtual nodes only"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_error_message",
                    models.TextField(blank=True, default=""),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Keepalive Configuration",
                "verbose_name_plural": "Keepalive Configuration",
            },
        ),
        migrations.CreateModel(
            name="NodePresenceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the transition was recorded.",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        help_text="Node last_seen value at transition.",
                    ),
                ),
                (
                    "offline_at",
                    models.DateTimeField(
                        help_text="Timestamp when node crossed offline threshold.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        default="offline_threshold",
                        help_text="Transition reason.",
                        max_length=64,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        help_text="Node associated with this offline transition.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_history",
                        to="stridetastic_api.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Presence History",
                "verbose_name_plural": "Node Presence History",
                "ordering": ["-time"],
            },
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="selected_nodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="When scope=selected, only these nodes are monitored.",
                related_name="keepalive_selected_configs",
                to="stridetastic_api.node",
            ),
        ),
    ]
