# Generated by Copilot for keepalive publish configuration

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stridetastic_api", "0008_keepalive_config_and_presence_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="keepaliveconfig",
            name="channel_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="channel_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="from_node",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="gateway_node",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="hop_limit",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="hop_start",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="payload_type",
            field=models.CharField(
                choices=[
                    ("reachability", "Reachability probe"),
                    ("traceroute", "Traceroute solicitation"),
                ],
                default="reachability",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="keepaliveconfig",
            name="interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="keepalive_configs",
                to="stridetastic_api.interface",
            ),
        ),
    ]
